### ISSUE TITLE
downgrade metasploit

### ISSUE THREAD

**Issue by gnu-like** [Dewalt-arch/pimpmykali#9]
**Downgrade msf6 to msf5 dependency conflict** 
```
Traceback (most recent call last):
        27: from /usr/bin/msfconsole:21:in `<main>'
        26: from /usr/bin/msfconsole:21:in `require'
        25: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        24: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        23: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        22: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        21: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
        20: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `require'
        19: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
        18: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
        17: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        16: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        15: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        14: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `require'
        13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `<top (required)>'
        12: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `require'
        11: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `<top (required)>'
        10: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `require'
         9: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `<top (required)>'
         8: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `require'
         7: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
         6: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
         5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
         4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `require'
         3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
         2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `require'
         1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class 
```

**Comment by Dewalt-arch** [comment]
Tested Downgrade to MSF5 function on Kali 2021.4a 
Downgraded From 6 -> 5 successfully without issue.
